management.tracing.enabled=false
management.observations.enabled=false
otel.java.global_autoconfigure_enabled=true
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://host.docker.internal:4318
otel.exporter.otlp.protocol=http/protobuf
otel.sdk.disabled=false
otel.service.name=otel-ms1

logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true
logging.level.io.opentelemetry=DEBUG