logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true


management.endpoints.web.exposure.include=httpexchanges,metrics
management.tracing.enabled= true
management.tracing.sampling.probability= 1.0
management.observations.enabled= true
management.tracing.otlp.endpoint = http://localhost:4318/v1/traces


logging.level.io.opentelemetry.exporter.otlp= DEBUG
logging.level.io.opentelemetry.sdk.trace.export= DEBUG
logging.level.io.opentelemetry.sdk.trace= DEBUG
logging.level.io.opentelemetry.sdk= DEBUG



